project/common/urls.py
from django.urls import path

from . import views

app_name = "common"
urlpatterns = [
    path("", views.MainView.as_view(), name="index"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("common.urls", namespace="common")),
    path("reports/", include("reports.urls", namespace="reports")),
    path("accounts/login/",  LoginView.as_view(template_name='common/login.html',
                                               redirect_authenticated_user=True,
                                               extra_context={'oidc_enabled': settings.OIDC_ENABLED,
                                                              'oidc_button_name': settings.OIDC_BUTTON_NAME},),
         name="login",),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path('oidc/', include('mozilla_django_oidc.urls')),
]

project/reports/urls.py
from django.urls import path

from . import views

app_name = "reports"
urlpatterns = [
    path("create/", views.CreateReportView.as_view(), name="create"),
    path("<int:report_id>/", views.GetReportView.as_view(), name="get"),
]

project/common/models.py
from django.db import models

# Create your models here.

project/common/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
# Create your views here.


class MainView(TemplateView):
    template_name = "common/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

project/common/templates/common/base.html
{% load i18n static bootstrap4%}
{% block bootstrap4_extra_head %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=True %}
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" /></link>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
    integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style/bootstrap-template.css' %}">
<link rel="stylesheet" href="{% static 'style/fontawesome-all.min.css' %}">
<link rel="stylesheet" href="{% static 'style/style.css' %}">
{%endblock%}

{% block bootstrap4_content %}
    {% block header %}
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <img id="logo-image" alt="Logo" src="{% static 'img/logo-dsm.png' %}">
                <a class="navbar-brand" href="{% url 'common:index' %}">DontSueMe</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'reports:create' %}">Создать отчет</a></li>
                    </ul>
                    <ul class="nav navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#"><span class="fas fa-user"></span> {{user.username}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}"><span class="fas fa-sign-out-alt"></span> Выйти</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}"><span class="fas fa-sign-in-alt"></span> Войти</a>
                        </li>
                        {% endif %}


                    </ul>
                </div>

            </div>
        </nav>
    {% endblock %}
    {% autoescape off %}
        {% for message in messages %}
            <div class="{{ message|bootstrap_message_classes }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="{% trans 'close' %}">&#215;</button>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endautoescape %}

            {% block content %}
                (no content)
            {% endblock %}

{% endblock %}

{% block bootstrap4_extra_script %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

project/common/templates/common/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}
    {% block title %}
    {% endblock %}
{% endblock %}

project/common/templates/common/index.html
{% extends 'common/base.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block title %}
DontSueMe Main
{% endblock %}

{% load i18n admin_modify %}

{% block content %}
    <section class="py-2">
        <div class="container my-2">
            <div class="row justify-content-center">
                <div class="col-lg-6 my-5 ">
                    <img id="index-image" alt="Logo" src="{% static 'img/logo-dsm.png' %}">
                </div>
                <div class="col-lg-6 my-5">
                    <h2>Добро пожаловать в цифровой сервис DontSueMe</h2>
                    <p class="lead">DontSueMe помогает своим клиентам избежать крупных штрафов.</p>
                    <p class="mb-0">Компания лидирует в своей отрасли, но работа с документами и
                    бесконечные согласования отнимают слишком много времени у юристов. Сервис помогает автомотизировать многие рутинные процессы</p>
                </div>

            </div>
        </div>
    </section>

{%endblock%}

project/common/templates/common/login.html
{% extends 'common/base.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% block title %}
DontSueMe Login
{% endblock %}

{% load i18n static %}
{% block header %}
{%endblock%}
{% block content %}

    <section class="py-2">
        <div class="container my-2">
            <div class="d-flex justify-content-center">
                {% if form.errors and not form.non_field_errors %}
                <p class="errornote">
                    {% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct
                    the errors below.{% endblocktranslate %}
                </p>
                {% endif %}

                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="errornote">
                    {{ error }}
                </p>
                {% endfor %}
                {% endif %}
                <div class="my-5">
                    <h2 style="text-align:center">Авторизация</h2>
                    <p style="text-align:center"><img id="logo-image" alt="Logo" src="{% static 'img/logo-dsm.png' %}"></p>
                    {% if user.is_authenticated %}
                        <p class="errornote">
                            {% blocktranslate trimmed %}
                            You are authenticated as {{ username }}, but are not authorized to
                            access this page. Would you like to login to a different account?
                            {% endblocktranslate %}
                        </p>
                    {% endif %}
                    <form role="form" method="post" action="{{ app_path }}" id="login-form">
                        {% csrf_token %}
                        {% bootstrap_field form.username show_label=False %}
                        {% bootstrap_field form.password show_label=False %}

                        {% bootstrap_button "Войти" button_type="submit" button_class="btn-light" %}
                        {% if oidc_enabled %}
                        {% url 'oidc_authentication_init' as oidc_url %}
                        {% bootstrap_button oidc_button_name button_type="link" href=oidc_url button_class="btn-light" %}
                        {% endif %}
                        {% bootstrap_button "Очистить" button_type="reset" button_class="btn-light" %}
                    </form>
                </div>
            </div>
        </div>
    </section>

</div>
{%endblock%}